export const navList = [{
  itemKey: 'home',
  iconType: 'crown',
  buttonVal: '首页',
  url: '/'
}, {
  itemKey: 'technology',
  iconType: 'experiment',
  buttonVal: '技术',
  itemArr: [{
    itemKey: 'react',
    buttonVal: 'react',
    iconType: 'code-sandbox',
    url: '/list/react'
  }, {
    itemKey: 'vue',
    buttonVal: 'vue',
    iconType: 'code-sandbox',
    url: '/list/vue'
  }, {
    itemKey: 'js',
    buttonVal: 'js',
    iconType: 'code-sandbox',
    url: '/list/js'
  }, {
    itemKey: 'css',
    buttonVal: 'css',
    iconType: 'code-sandbox',
    url: '/list/js'
  }, {
    itemKey: 'node',
    buttonVal: 'node',
    iconType: 'code-sandbox',
    url: '/list/node'
  }]
}, {
  itemKey: 'life',
  iconType: 'instagram',
  buttonVal: '生活',
  url: '/list/life'
}, {
  itemKey: 'say',
  iconType: 'compass',
  buttonVal: '碎碎念',
  url: '/say'
}, {
  itemKey: 'about',
  iconType: 'message',
  buttonVal: '关于我',
  url: '/about'
}, {
  itemKey: 'friend',
  iconType: 'heart',
  buttonVal: '友人帐',
  url: '/friend'
}]