export const navList = [{
  itemKey: 'home',
  iconType: 'crown',
  buttonVal: '首页',
  url: '/'
}, {
  itemKey: 'list',
  iconType: 'experiment',
  buttonVal: '技术',
  url: '/list'
}, {
  itemKey: 'say',
  iconType: 'instagram',
  buttonVal: '碎碎念',
  url: '/say'
}, {
  itemKey: 'about',
  iconType: 'smile',
  buttonVal: '关于我',
  url: '/about'
}, {
  itemKey: 'friend',
  iconType: 'heart',
  buttonVal: '友人帐',
  url: '/friend'
}, {
  itemKey: 'leave-msg',
  iconType: 'message',
  buttonVal: '留言',
  url: '/leave-msg'
}]